mixed-port: 7890
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
dns:
  enable: true
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114

# 这里可以添加您的代理配置
proxies:
  # 示例代理配置，请替换为您自己的配置
  # - name: "示例代理"
  #   type: ss
  #   server: server.com
  #   port: 443
  #   cipher: chacha20-ietf-poly1305
  #   password: "password"

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - DIRECT
      # - 示例代理

rules:
  - DOMAIN-SUFFIX,google.com,PROXY
  - DOMAIN-SUFFIX,github.com,PROXY
  - DOMAIN-SUFFIX,githubusercontent.com,PROXY
  - GEOIP,CN,DIRECT
  - MATCH,DIRECT
